{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://localhost:3000",
      "description": "Localhost"
    },
    {
      "url": "https://clin.cr-ste-justine.xyz/api",
      "description": "QA"
    }
  ],
  "info": {
    "version": "1.x",
    "license": {
      "name": "GNU Affero General Public License v3.0",
      "url": "https://github.com/cr-ste-justine/clin-proxy-api/blob/master/LICENSE"
    },
    "title": "Authentication Service",
    "description": "Authentication REST API Service; This service provides a JWT HTTPS-Only Secure Cookie used by other services from clin-proxy-api for Authentication and Authorization Access Control purposes.\n"
  },
  "paths": {
    "/auth/health": {
      "get": {
        "tags": [
          "Health Check"
        ],
        "summary": "Returns health status of the service",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HealthSuccess"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    },
    "/auth": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Log user in",
        "responses": {
          "200": {
            "description": "Success",
            "headers": {
              "Set-Cookie": {
                "schema": {
                  "type": "string",
                  "example": "token=abcde12345; Path=/; HttpOnly; Secure"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginSuccess"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserForm",
                "required": true
              }
            }
          }
        }
      },
      "get": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Authentication"
        ],
        "summary": "Get logged in user identity",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginSuccess"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Authentication"
        ],
        "summary": "Log user out",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogoutSuccess"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    },
    "/auth/token": {
      "post": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Token Refresh Route"
        ],
        "summary": "Refresh user",
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefreshSuccess"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "cookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "token"
      }
    },
    "schemas": {
      "UserForm": {
        "properties": {
          "username": {
            "description": "User supplied email",
            "type": "string",
            "format": "email",
            "example": "practitioner@cr-ste-justine.xyz"
          },
          "password": {
            "description": "User supplied password",
            "type": "string",
            "format": "password",
            "example": "qwerty123"
          }
        }
      },
      "LoginSuccess": {
        "title": "Login",
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "example": {
          "timestamp": 1587404265303,
          "message": "Ok",
          "data": {
            "user": {
              "username": "practitioner@cr-ste-justine.xyz",
              "firstName": "Practitioner",
              "groups": [],
              "roles": [
                "clin_practitioner"
              ]
            }
          }
        }
      },
      "RefreshSuccess": {
        "title": "Refresh",
        "type": "object",
        "example": {
          "timestamp": 1587404265303,
          "message": "Ok",
          "data": {
            "user": {
              "username": "practitioner@cr-ste-justine.xyz",
              "firstName": "Practitioner",
              "groups": [],
              "roles": [
                "clin_practitioner"
              ]
            }
          },
          "token": {
            "value": "string",
            "expiry": "long"
          }
        }
      },
      "LogoutSuccess": {
        "title": "Logout",
        "type": "object"
      },
      "HealthSuccess": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403130516,
          "message": "Ok",
          "data": {
            "uid": "12a6smj1353k98qu26w",
            "cuid": "12a6smj1353k98qu26t",
            "status": "OK",
            "packageVersion": "1.3.6",
            "defaultApiVersion": 1,
            "currentApiVersion": 1,
            "apiVersions": [
              1
            ],
            "uptime": 5388,
            "served": 1
          }
        }
      },
      "Error401": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "Unauthorized",
          "data": {
            "messages": [
              "Halp! I has the forgottenz."
            ]
          }
        }
      },
      "Error403": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "Forbidden",
          "data": {
            "messages": [
              "Halp! I see new lock and I has no key nooo monies."
            ]
          }
        }
      },
      "Error404": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "NotFound",
          "data": {
            "messages": [
              "Halp! I has confused."
            ]
          }
        }
      },
      "Error500": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "InternalError",
          "data": {
            "messages": [
              "Halp! I has error."
            ]
          }
        }
      }
    },
    "requestBodies": {}
  }
}
