{
  "openapi": "3.0.0",
  "info": {
    "version": "1.x",
    "title": "Meta API Service",
    "description": "Meta API Service; statement and profile sub-resources\n",
    "license": {
      "name": "GNU Affero General Public License v3.0",
      "url": "https://github.com/cr-ste-justine/clin-proxy-api/blob/master/LICENSE"
    }
  },
  "servers": [
    {
      "url": "https://localhost:7000",
      "description": "Localhost"
    },
    {
      "url": "https://clin.cr-ste-justine.xyz/api",
      "description": "QA"
    }
  ],
  "paths": {
    "/meta/health": {
      "get": {
        "tags": [
          "Service Health Check"
        ],
        "summary": "Returns the health status of the service.",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Health"
                }
              }
            }
          }
        }
      }
    },
    "/meta/statement": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Statement resource"
        ],
        "summary": "Returns all the statements for the current user.",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/statementResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Statement resource"
        ],
        "summary": "create a new statement for the current user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Statement"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/statementResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Statement resource"
        ],
        "summary": "Update a  statement for the current user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Statement"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/statementResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "404": {
            "description": "NotFound",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error404"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    },
    "/meta/statement/{uid}": {
      "delete": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Statement resource"
        ],
        "summary": "delete a statement for the current user",
        "parameters": [
          {
            "in": "path",
            "name": "uid",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "statement UID of the current user to delete"
          }
        ],
        "responses": {
          "204": {
            "description": "The resource was deleted successfully."
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    },
    "/meta/profile": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Profile resource"
        ],
        "summary": "Returns the profile for the current user.",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/profileResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Profile resource"
        ],
        "summary": "create a profile for the current user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/profileRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/profileResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Profile resource"
        ],
        "summary": "Update a profile for the current user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/profileRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/profileResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "404": {
            "description": "NotFound",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error404"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    },
    "/meta/profile/{uid}": {
      "delete": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": [
          "Profile resource"
        ],
        "summary": "delete the profile for the current user",
        "parameters": [
          {
            "in": "path",
            "name": "uid",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "profile UID of the current user to delete"
          }
        ],
        "responses": {
          "204": {
            "description": "The resource was deleted successfully."
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error401"
                }
              }
            }
          },
          "500": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "cookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "token"
      }
    },
    "schemas": {
      "Health": {
        "title": "Health Check",
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1553284037677,
          "message": "Ok",
          "data": {}
        }
      },
      "SQON": {
        "title": "Structured Query Object Notation",
        "properties": {
          "key": {
            "type": "string"
          },
          "instructions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    },
                    "index": {
                      "type": "integer"
                    },
                    "values": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "operand": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "example": {
          "key": "a62358e0-2023-11ea-a4ec-97496af1912d",
          "instructions": [
            {
              "type": "filter",
              "data": {
                "id": "variant_type",
                "type": "generic",
                "index": 1,
                "values": [
                  "deletion"
                ],
                "operand": "all"
              }
            }
          ]
        }
      },
      "Statement": {
        "title": "Statement resource",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "queries": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/SQON"
            }
          },
          "uid": {
            "type": "string",
            "nullable": true
          }
        },
        "example": {
          "title": "My one statement",
          "uid": "Gc3hLXIBtsRakoBUb88l",
          "description": "My one statement",
          "queries": [
            {
              "key": "a62358e0-2023-11ea-a4ec-97496af1912d",
              "instructions": [
                {
                  "type": "filter",
                  "data": {
                    "id": "variant_type",
                    "type": "generic",
                    "index": 1,
                    "values": [
                      "deletion"
                    ],
                    "operand": "all"
                  }
                }
              ]
            }
          ]
        }
      },
      "Profile": {
        "title": "Profile resource",
        "type": "object",
        "properties": {
          "defaultStatement": {
            "type": "string"
          },
          "patientTableConfig": {
            "type": "string"
          },
          "variantTableConfig": {
            "type": "string"
          },
          "lastUpdatedOn": {
            "type": "integer"
          },
          "practitionerId": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "uid": {
            "type": "string",
            "nullable": true
          }
        },
        "example": {
          "defaultStatement": "",
          "patientTableConfig": "{}",
          "variantTableConfig": "{}",
          "lastUpdatedOn": 1589920914967,
          "practitionerId": "PR00610",
          "organizationId": "OR00202",
          "uid": "hUG7LnIB2vbrMnq1AppV"
        }
      },
      "profileRequest": {
        "title": "Profile resource",
        "type": "object",
        "properties": {
          "defaultStatement": {
            "type": "string"
          },
          "patientTableConfig": {
            "type": "string"
          },
          "variantTableConfig": {
            "type": "string"
          },
          "lastUpdatedOn": {
            "type": "integer"
          },
          "practitionerId": {
            "type": "object"
          },
          "organizationId": {
            "type": "object"
          },
          "uid": {
            "type": "string",
            "nullable": true
          }
        },
        "example": {
          "defaultStatement": "",
          "patientTableConfig": {},
          "variantTableConfig": {},
          "lastUpdatedOn": 1589920914967,
          "practitionerId": "PR00610",
          "organizationId": "OR00202",
          "uid": "hUG7LnIB2vbrMnq1AppV"
        }
      },
      "profileResponse": {
        "title": "Profile response",
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "properties": {
              "total": {
                "type": "integer"
              },
              "hits": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "_index": {
                      "type": "string"
                    },
                    "_type": {
                      "type": "string"
                    },
                    "_id": {
                      "type": "string"
                    },
                    "_score": {
                      "type": "number",
                      "format": "float"
                    },
                    "_source": {
                      "$ref": "#/components/schemas/Profile"
                    }
                  }
                }
              }
            }
          }
        },
        "example": {
          "timestamp": 1553284037677,
          "message": "Ok",
          "data": {
            "total": 1,
            "hits": [
              {
                "_index": "profile",
                "_type": "_doc",
                "_id": "hEGrLnIB2vbrMnq13pod",
                "_score": 0.6931472,
                "_source": {
                  "defaultStatement": "",
                  "patientTableConfig": "{}",
                  "variantTableConfig": "{}",
                  "lastUpdatedOn": 1589920914967,
                  "practitionerId": "PR00610",
                  "organizationId": "OR00202"
                }
              }
            ]
          }
        }
      },
      "statementResponse": {
        "title": "Statement response",
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "$ref": "#/components/schemas/Statement"
          }
        },
        "example": {
          "timestamp": 1553284037677,
          "message": "Ok",
          "data": {
            "title": "My one statement",
            "description": "My one statement",
            "uid": "Gc3hLXIBtsRakoBUb88l",
            "queries": [
              {
                "key": "a62358e0-2023-11ea-a4ec-97496af1912d",
                "instructions": [
                  {
                    "type": "filter",
                    "data": {
                      "id": "variant_type",
                      "type": "generic",
                      "index": 1,
                      "values": [
                        "deletion"
                      ],
                      "operand": "all"
                    }
                  }
                ]
              }
            ]
          }
        }
      },
      "Error500": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "InternalError",
          "data": {
            "messages": [
              "Halp! I has error."
            ]
          }
        }
      },
      "Error401": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "Unauthorized",
          "data": {
            "messages": [
              "Halp! I has the forgottenz."
            ]
          }
        }
      },
      "Error404": {
        "type": "object",
        "properties": {
          "timestamp": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "items": {
              "type": "object"
            }
          }
        },
        "example": {
          "timestamp": 1587403307565,
          "error": "NotFound",
          "data": {
            "messages": []
          }
        }
      }
    }
  }
}
